sudo: required
language: go
go:
  - 1.13.x
install:
  - # Do nothing. This is needed to prevent default install action
  - # "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(go fmt ./...)
  - go vet .
  - sudo `which go` test -v -race ./...
